# cloudbuild.yaml for datahub-frontend
steps:
# 1단계: DataHub Frontend 도커 이미지 빌드
- name: 'gradle:8.5-jdk17'
  entrypoint: './gradlew'
  args:
    - ':docker:datahub-frontend-react:buildImage'
    - '-PdockerRegistry=${_GAR_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}'
    - '-PdockerTag=${_VERSION}'

# 2단계: Artifact Registry에 이미지 푸시
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_GAR_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}/datahub-frontend-react:${_VERSION}']

images:
- '${_GAR_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_REPO_NAME}/datahub-frontend-react:${TAG_NAME}'

substitutions:
  _GCP_PROJECT_ID: hyperscale-ai-442809
  _GAR_LOCATION: us-west1
  _REPO_NAME: asset-data-analytic-platform-dev
  _VERSION: v0.0.1

options:
  logging: GCS_ONLY
  logs_bucket: 'gs://gnaix-dev-logs-bucket'
